nelmio_api_doc:
    documentation:
        info:
            title: API
            description: API for Conference registration
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api/v1
