imports:
    - { resource: ../../../doc/api/nelmio/v1/ }}

nelmio_api_doc:
    documentation:
        info:
            title: Conferences
            description: API for Conference registration
            version: 1.0.0
    areas:
        default:
            path_patterns:
                - ^/ignore-this-route
        v1:
            path_patterns:
                - ^/api/v1(?!/doc(|\.json)$)
